[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#[[patches]]
# [patches.pattern]
# target = "cardarea.lua"
# pattern = '''self.children.area_uibox = UIBox{'''
# position = "before"
# match_indent = true
# payload = '''
# if (self == G.jokers) or (self == G.felijo_totems) then
#     local text = localize((self == G.jokers) and 'felijo_toggle_to_totems' or 'felijo_toggle_to_jokers')
#     if (not self.children.felijo_totem_toggle_uibox) then
#         self.children.felijo_totem_toggle_uibox = UIBox{
#             definition = 
#                 {n=G.UIT.ROOT, config = {align = 'bl', colour = G.C.CLEAR}, nodes={
#                     {n=G.UIT.R, config={align = "cl", minh = 0.1, minw = 0.9, padding = 0.1, r = 0.1, no_fill = true}, nodes={}},
#                     {n=G.UIT.R, config={align = "cl", minh = 0.4, minw = 0.9, padding = 0.1, r = 0.1, hover = true, colour =G.ARGS.LOC_COLOURS.felijo_ttm, button = "toggle_totems", func = "felijo_can_toggle_totem", shadow = true, no_fill = true}, nodes={
#                         {n=G.UIT.T, config={text = text, scale = 0.2, colour = G.C.UI.TEXT_LIGHT}}
#                     }}
#                 }},
#             config = { align = 'bl', offset = {x=self.T.w-0.7,y=-0.1}, major = self, parent = self}
#         }
#     end
# end
# '''

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''self.children.area_uibox:draw()'''
position = "after"
match_indent = true
payload = '''
if self.children.felijo_totem_toggle_uibox and G.GAME.felijo_totem_obtained_item then
    self.children.felijo_totem_toggle_uibox:draw()
end
'''
