[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
if card.config.center.set == 'Tarot' or card.config.center.set == 'Planet' then 
  G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
      G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
          G.GAME.last_tarot_planet = card.config.center_key
            return true
        end
      }))
        return true
    end
  }))
end
'''
position = "after"
payload = '''
if card.config.center.set == 'felijo_tier2_planet' or 
card.config.center.set == 'felijo_tier3_planet' or 
card.config.center.set == 'felijo_tier4_planet' or 
card.config.center.set == 'felijo_tier2_tarot' or 
card.config.center.set == 'felijo_tier3_tarot' or 
card.config.center.set == 'felijo_tier4_tarot' then 
  G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
      G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
          G.GAME.last_tarot_planet = card.config.center_key
            return true
        end
      }))
        return true
    end
  }))
end

if card.config.center.set == 'Consumeables' then 
  G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
      G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
          G.GAME.last_consumable_used = card.config.center_key
            return true
        end
      }))
        return true
    end
  }))
end
'''
match_indent = true